'use client';
import {FormEvent,useRef,useState} from 'react';

const makeProjects=(folder:string,count:number)=>Array.from({length:count},(_,index)=>({image:`/portfolio/${folder}/${String(index+1).padStart(2,'0')}.jpg`,alt:`Projeto selecionado de ${folder.replace('-',' ')}`}));
const services=[
 {title:'Branding + Identidade',price:'a partir de R$ 1.800',summary:'Estratégia e expressão visual para dar clareza e personalidade ao que você quer apresentar.',work:'estratégia · identidade · aplicações',cover:'/portfolio/branding/01.jpg',projects:makeProjects('branding',5)},
 {title:'Social Media',price:'de R$ 350 a R$ 1.800/mês',summary:'Conteúdo e direção visual para comunicar com presença, ritmo e consistência.',work:'direção · conteúdo · campanhas',cover:'/portfolio/social-media/03.jpg',projects:makeProjects('social-media',10)},
 {title:'Web Design',price:'a partir de R$ 3.000',summary:'Landing pages e sites pensados para apresentar ideias, serviços e projetos com clareza.',work:'landing pages · sites · responsividade',cover:'/portfolio/web-design/02.jpg',projects:makeProjects('web-design',6)},
 {title:'Design Editorial',price:'a partir de R$ 400',summary:'Projeto gráfico para histórias, publicações e materiais que pedem uma leitura bem construída.',work:'capas · spreads · publicações',cover:'/portfolio/editorial/04.jpg',projects:makeProjects('editorial',4)},
 {title:'Embalagens',price:'a partir de R$ 900',summary:'Soluções visuais para produtos, presentes e experiências que ganham forma.',work:'produto · linha · mockups',cover:'/portfolio/embalagens/01.jpg',projects:makeProjects('embalagens',2)}
];
const socialOffers=[
 {title:'Diagnóstico',price:'R$ 350',text:'Uma leitura estratégica para entender o cenário atual e enxergar os próximos passos com clareza.'},
 {title:'Diagnóstico + Enxoval',price:'R$ 650',text:'Organização do perfil, direção visual e uma base de conteúdo para começar com mais consistência.'},
 {title:'Estruturação Completa',price:'R$ 1.200',text:'Estratégia, identidade para as redes e conteúdo inicial reunidos em uma presença bem estruturada.'},
 {title:'Operação Recorrente',price:'R$ 1.800/mês',text:'Planejamento e produção mensal para manter a comunicação ativa, coerente e interessante.'}
];

export default function Home(){
 const[menu,setMenu]=useState(false);const[open,setOpen]=useState<number|null>(null);const[selected,setSelected]=useState<number|null>(null);const[activeService,setActiveService]=useState(0);const[formStatus,setFormStatus]=useState<'idle'|'sending'|'sent'|'error'>('idle');const serviceTrack=useRef<HTMLDivElement>(null);
 async function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();
  setFormStatus('sending');
  const form=e.currentTarget;
  try{
   const response=await fetch('https://formspree.io/f/xnpqvbvy',{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});
   if(!response.ok)throw new Error('Não foi possível enviar');
   form.reset();
   setFormStatus('sent');
  }catch{
   setFormStatus('error');
  }
 }
 function centerService(index:number){const next=Math.max(0,Math.min(services.length-1,index));setActiveService(next);serviceTrack.current?.children[next]?.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})}
 function slide(direction:number){centerService(activeService+direction)}
 function syncActive(){const track=serviceTrack.current;if(!track)return;const center=track.scrollLeft+track.clientWidth/2;let nearest=0;let distance=Infinity;Array.from(track.children).forEach((child,i)=>{const el=child as HTMLElement;const d=Math.abs(el.offsetLeft+el.offsetWidth/2-center);if(d<distance){distance=d;nearest=i}});setActiveService(nearest)}
 return <main className="rd">
  <header className="rdHeader"><a href="#inicio" className="rdLogo rdBrandLogo" aria-label="Gio — início"><img src="/logo-primary.svg" alt="Gio"/></a><button onClick={()=>setMenu(!menu)} className="rdMenu">Menu</button><nav className={menu?'open':''}><a href="#sobre">Sobre</a><a href="#servicos">Serviços</a><a href="#portfolio">Portfólio</a><a href="#contato">Contato</a></nav><a className="rdHeaderCta" href="#contato">Vamos trabalhar juntos ↗</a></header>

  <section className="rdHero rdHeroCustom" id="inicio"><picture className="rdHeroPicture"><source media="(max-width:760px)" srcSet="/hero-mobile.svg"/><img className="rdHeroArtwork" src="/hero-desktop.svg" alt="" aria-hidden="true"/></picture><div className="rdHeroCtas"><a href="#portfolio">Ver portfólio</a><a href="#contato">Iniciar projeto <span aria-hidden="true">↗</span></a></div><h1 className="rdSrOnly">Uma marca inteira, em cada ponto de contato.</h1><p className="rdSrOnly">Branding, identidade, social media, web, editorial e embalagens construídos com a mesma direção.</p></section>
  <section className="rdIntro" id="sobre"><div className="rdPhoto"><img src="/gio-about-v2.png" alt="Retrato de Giovanna Pimenta"/></div><div className="rdIntroCopy"><span className="rdPill">Sobre mim</span><h2><span>Giovanna Pimenta,</span><span>mas pode me chamar de Gio.</span></h2><div className="rdTags"><span>Branding</span><span>Social</span><span>Web</span><span>Editorial</span><span>Embalagem</span></div><p>Carioca, 23 anos e designer gráfica graduada em Design Gráfico pela Universidade do Estado de Santa Catarina (UDESC). Tenho foco no desenvolvimento de soluções visuais criativas e funcionais, atuando em projetos que envolvem identidade visual, comunicação digital e materiais gráficos. O que mais me move é usar o design para criar conexões autênticas, consistentes e marcantes.</p><a href="#contato">Vamos criar juntos? ↗</a></div></section>

  <section className="rdServiceShowcase" id="servicos"><span id="portfolio" className="rdAnchor"/><div className="rdServiceHead"><div><span className="rdPill light">Serviços + portfólio</span><h2>Encontre o próximo passo<br/>para a sua ideia.</h2></div><div className="rdArrows"><button onClick={()=>slide(-1)} aria-label="Serviços anteriores">←</button><button onClick={()=>slide(1)} aria-label="Próximos serviços">→</button></div></div><div className="rdServiceTrack" ref={serviceTrack} onScroll={syncActive}>{services.map((service,i)=><button className={'rdServiceCard '+(activeService===i?'active':'')} key={service.title} onClick={()=>{setActiveService(i);setSelected(i)}}><div className="rdCardVisual"><img src={service.cover} alt=""/></div><h3>{service.title}</h3><p>{service.summary}</p><div className="rdCardFooter"><strong>{service.price}</strong><span className="rdOpen">Ver projetos ↗</span></div></button>)}</div></section>

  <section className="rdWhy"><div className="rdWhyCopy"><span className="rdPill coral">Como trabalho</span><h2>Clareza em cada etapa. Menos retrabalho no final.</h2><p>O projeto avança por entregas e aprovações: primeiro entendemos, depois definimos a direção, desenvolvemos o sistema e preparamos os arquivos finais. Prazos consideram agenda e o ritmo dos retornos.</p><ol><li><b>01</b><span><strong>Entender</strong>Briefing, contexto e objetivos.</span></li><li><b>02</b><span><strong>Direcionar</strong>Conceitos, referências e caminho criativo.</span></li><li><b>03</b><span><strong>Criar</strong>Desenvolvimento da direção escolhida.</span></li><li><b>04</b><span><strong>Entregar</strong>Arquivos organizados e preparados para uso.</span></li></ol><a href="#contato">Iniciar um projeto ↗</a></div></section>

  <section className="rdQuote"><blockquote>Uma marca pode estar no site, na embalagem, nas redes e em uma publicação.<br/><em>Ela ainda precisa parecer a mesma marca.</em></blockquote><span>Design como sistema, não como peças soltas</span></section>

  <section className="rdFaq"><span className="rdPill coral">Para criar juntas</span><h2>Dúvidas antes do primeiro passo</h2><p className="rdFaqIntro">Você não precisa chegar com tudo resolvido. A primeira conversa também serve para entender o momento da sua marca e encontrar o caminho que faz mais sentido.</p><div>{[['Como saber qual serviço faz sentido para a minha marca?','Conte brevemente o seu momento e o que você deseja transformar. A partir disso, eu indico o formato de projeto mais coerente com a sua necessidade.'],['Você trabalha com marcas que estão começando?','Sim. Posso ajudar tanto marcas que ainda estão tomando forma quanto negócios que já existem e precisam ganhar mais clareza, consistência e presença.'],['Como funciona o primeiro contato?','Você compartilha algumas informações pelo formulário e eu retorno para conversarmos com mais contexto sobre objetivos, prioridades e possibilidades.'],['Posso combinar mais de um serviço?','Sim. Identidade, conteúdo, web, editorial e embalagem podem ser pensados de forma integrada para que todos os pontos de contato falem a mesma língua.'],['Preciso chegar com um briefing pronto?','Não. Ter referências e objetivos ajuda, mas não é preciso organizar tudo antes. Eu conduzo as perguntas necessárias para transformar a ideia em uma direção clara.']].map((item,i)=><button key={item[0]} onClick={()=>setOpen(open===i?null:i)}><span>{item[0]}</span><b>{open===i?'−':'+'}</b>{open===i&&<p>{item[1]}</p>}</button>)}</div></section>

  <section className="rdContact" id="contato"><div><span className="rdPill light">Iniciar projeto</span><h2>O que sua marca<br/>precisa construir <em>agora?</em></h2><p>Conte um pouco sobre o seu momento. A partir daqui, começamos a transformar intenção em uma direção clara.</p></div><form onSubmit={submit}><input type="hidden" name="_subject" value="Novo projeto pelo site da Gio"/><label>Nome<input name="nome" required placeholder="Como posso te chamar?"/></label><label>Empresa ou marca<input name="empresa_ou_marca" placeholder="Nome da marca"/></label><label>E-mail<input name="email" required type="email" placeholder="voce@email.com"/></label><label>WhatsApp<input name="whatsapp" placeholder="(00) 00000-0000"/></label><label>Serviço desejado<select name="servico_desejado" defaultValue=""><option value="" disabled>Selecione</option><option>Branding + Identidade</option><option>Social Media</option><option>Web Design</option><option>Design Editorial</option><option>Embalagem</option><option>Outro</option></select></label><label>Momento da marca<select name="momento"><option>Tenho uma ideia inicial</option><option>Já tenho marca e quero evoluir</option><option>Já tenho briefing e conteúdo</option><option>Busco um trabalho recorrente</option></select></label><label>Faixa de investimento<select name="investimento"><option>Prefiro conversar</option><option>Até R$ 1.500</option><option>R$ 1.500 a R$ 3.000</option><option>R$ 3.000 a R$ 5.000</option><option>Acima de R$ 5.000</option></select></label><label>Quando gostaria de começar?<select name="prazo"><option>Assim que houver disponibilidade</option><option>Em até 30 dias</option><option>Em 1 a 3 meses</option><option>Ainda estou planejando</option></select></label><label>Conte sobre o projeto<textarea name="projeto" required rows={4} placeholder="O que você gostaria de transformar na sua marca?"/></label><button type="submit" disabled={formStatus==='sending'}>{formStatus==='sending'?'Enviando...':'Quero conversar sobre meu projeto ↗'}</button>{formStatus==='sent'&&<p role="status">Obrigada! Recebi suas informações e entrarei em contato em breve.</p>}{formStatus==='error'&&<p role="alert">Não foi possível enviar agora. Tente novamente em alguns instantes.</p>}</form></section>
  <footer className="rdFooter"><a className="rdLogo rdBrandLogo rdBrandLogoFooter" href="#inicio" aria-label="Gio — voltar ao início"><img src="/logo-primary.svg" alt="Gio"/></a><div><a href="https://www.instagram.com/pmtgii/" target="_blank" rel="noreferrer">Instagram</a><a href="https://www.behance.net/giovannapimenta2" target="_blank" rel="noreferrer">Behance</a><a href="https://www.linkedin.com/in/giovannapimenta2" target="_blank" rel="noreferrer">LinkedIn</a></div></footer>
  {selected!==null&&<div className="rdServiceBackdrop" onMouseDown={()=>setSelected(null)}><div className="rdServiceModal rdPortfolioModal" role="dialog" aria-modal="true" aria-label={services[selected].title} onMouseDown={event=>event.stopPropagation()}><button className="rdModalClose" onClick={()=>setSelected(null)} aria-label="Fechar">×</button><header className="rdPortfolioHeader"><div><span className="rdPill">Serviço</span><h2>{services[selected].title}</h2><p>{services[selected].summary}</p></div><div className="rdPortfolioAction"><strong>{services[selected].price}</strong><a href="#contato" onClick={()=>setSelected(null)}>Conversar sobre este serviço ↗</a></div></header>{selected===1&&<section className="rdSocialOffers"><div className="rdProjectIntro"><span>Encontre o formato ideal</span><small>4 possibilidades</small></div><div>{socialOffers.map((offer,index)=><article key={offer.title}><small>{String(index+1).padStart(2,'0')}</small><h3>{offer.title}</h3><p>{offer.text}</p><strong>{offer.price}</strong></article>)}</div></section>}<div className="rdProjectIntro"><span>Projetos selecionados</span><small>{services[selected].projects.length} imagens</small></div><div className={'rdProjectGrid rdProjectGrid'+selected}>{services[selected].projects.map((project,index)=><figure key={project.image}><img src={project.image} alt={`${project.alt} ${index+1}`} loading="lazy"/></figure>)}</div></div></div>}
 </main>
}
